### ISSUE TITLE
How to run the server and app-shell?

### ISSUE THREAD

**Issue by renyaoxiang** [swathisprasad/angular-app-shell#1]
Hello, How to run the server and app-shell?

**Comment by swathisprasad** [comment]
@renyaoxiang, please run 'ng serve' to run the application. I have described in this article https://medium.com/@swathisprasad/getting-started-with-app-shell-using-angular-7-e4d55e4e5d2c

**Comment by renyaoxiang** [comment]
Thanks

**Comment by swathisprasad** [comment]
Closing this issue as there is no action required.
